[versions]
kotlin = "2.0.21"
gradle = "8.5.2"
dependencyVersionsPlugin = "0.51.0"
nexusSonatype = "2.0.0"
dokka = "1.9.20"
coroutines = "1.9.0"
composeMultiplatform = "1.7.0"

# Tweener
tweenerBom = "2.1.4"

# Android
androidActivity = "1.9.3"

[libraries]
compose-multiplatform-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "composeMultiplatform" }

# Tweener
tweener-bom = { group = "io.github.tweener", name = "kmp-bom", version.ref = "tweenerBom" }
tweener-common = { group = "io.github.tweener", name = "kmp-common" }

# Coroutines
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }

# Android
android-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidActivity" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidActivity" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "gradle" }
android-application = { id = "com.android.application", version.ref = "gradle" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
dependency-versions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersionsPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
nexus-sonatype = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusSonatype" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
