[versions]
kotlin = "2.2.20"
gradle = "8.13.0"
composeMultiplatform = "1.9.0"
material3 = "1.9.0-beta06"
dependencyVersionsPlugin = "0.52.0"
mavenPublish = "0.34.0"
dokka = "2.0.0"
coroutines = "1.10.2"
kmpKit = "1.0.10"
androidActivity = "1.11.0"
firebaseGitLiveApp = "2.3.0" # Firebase for KMP https://firebaseopensource.com/projects/gitliveapp/firebase-kotlin-sdk/
googleServicesPlugin = "4.4.3"
androidStartup = "1.2.0"

[libraries]
compose-multiplatform-material3 = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "material3" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kmpkit = { group = "io.github.tweener", name = "kmpkit", version.ref = "kmpKit" }
android-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidActivity" }
android-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidActivity" }
android-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidStartup" }

firebase-messaging = { group = "dev.gitlive", name = "firebase-messaging", version.ref = "firebaseGitLiveApp" }
firebase-installations = { group = "dev.gitlive", name = "firebase-installations", version.ref = "firebaseGitLiveApp" }

[bundles]
gitlive-firebase = ["firebase-messaging", "firebase-installations"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "gradle" }
android-library = { id = "com.android.library", version.ref = "gradle" }
dependency-versions = { id = "com.github.ben-manes.versions", version.ref = "dependencyVersionsPlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-nativeCocoaPods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesPlugin" }
